### ISSUE TITLE
Make it easier to override default styles with CSS

### ISSUE THREAD

**Issue by AmeliaBR** [Shopify/buy-button-js#341]
I shouldn't have to explicitly set `color: inherit` and `font: inherit` in dozens of places in a JSON object just to have CSS styles behave the way CSS styles are supposed to behave.

For example:

- add an option to turn off default styles altogether for each component
- add an example to the docs of how to include your own stylesheet with an extra template
- ideally, separate the default styles into sub-categories (layout, animations, color scheme, typography) and create options to include or exclude the default styles of each type

The above would at least make it possible for someone working with a web designer to use the Buy Button functionality but their own styles (while still maintaining the encapsulation of an `iframe`).

For smaller-level overrides, and  to make it easier to customize styles, with less repetitive code, consider:

- relying on style inheritance more uniformly in the default styles
- supporting all complex selectors, not only pseudoclasses, in the nested styles
- allowing store owners to create custom color palettes and their own default typographic classes, and then applying them to each sub-component instead of applying the raw values individually

**Comment by tessalt** [comment]
what would be the use case for wanting to keep the encapsulation of the iframe if you want to disable all the default styles?

**Comment by AmeliaBR** [comment]
> what would be the use case for wanting to keep the encapsulation of the iframe if you want to disable all the default styles?

To encapsulate behavior/DOM, to encapsulate one's own styles. For my case, I'm inserting the product listings right in my main page, but I'm keeping the shopping cart as an `iframe`. I probably don't _need_ to do it that way, but it seems to make sense.

But the ideal case for me would be to be able to apply your layout styles & animations, but easily reset colors and typography without having to reset them on every single element via the config object.

**Comment by tessalt** [comment]
you can selectively disable the iframes per component (ex disable it for product but not for the cart). 

Limiting selectors was an intentional decision, to prevent the DOM from becoming an API that we could then never change without breaking user sites (as did happen when we allowed custom css on checkout). As such we only expose certain selectors that should allow for most customization use cases. To avoid literal duplication, you can save styles as variables as the config object is javascript (not json): 

```
var buttonStyles = {
   'font-size': '12px',
   'background-color': 'blue',
   'border-radius': '10px'
}

styles: {
   product: {
     button: buttonStyles,
   },
   cart: {
      button: buttonStyles,
   }
}
```

Note that the styles do cascade, so styles you set on the top-level component (ex product.styles.product) will cascade normally (you may need !important however to override specificity)
