### ISSUE TITLE
Modifying templates not working for cart or lineItem models

### ISSUE THREAD

**Issue by sniepoort** [Shopify/buy-button-js#368]
The template for example for subtotal, does not seem to get triggered. And returning anything from the viewData function doesn't do anything.
Same issues on lineItem. Can't log 'this'. However, it is returning what I put in the template, but not executing the custom viewData function.
My code has been working for other things, like product or productModal

```javascript
      "cart": {
        "popup": false,
        "contents": {
          "button": true
        },
        "text": {
          "notice": "Fragt vil blive tillagt senere",
          "empty": "Din kurv er tom",
          "button": "AFSLUT KØB"
        },
        "styles": {
          "footer": {
            "background-color": "#ffffff"
          }
        },
        "templates": {
          "subtotal": '<p class="shopify-buy__cart__subtotal__price" data-element="cart.subtotal">{{data.modifySubtotal}}</p>',
        },
        "viewData": {
          "modifySubtotal": function () {
            console.log(this)
            // var price = this.data.formattedPrice.replace(',','').replace(',-', '').replace('-', '');
            return 'testing'
          },
        },
      },

"lineItem": {
        "viewData": {
          "modifyLinePrice": function () {
            // var price = this.data.formattedLinePrice.replace(',','').replace(',-', '').replace('-', '');
            return 'xxx'
          },
        },
        "templates": {
          "price": '<span class="shopify-buy__cart-item__price" data-element="lineItem.price">{{data.modifyLinePrice}}</span>',
        },
      },
```

**Comment by tanema** [comment]
There are two problems. 

There is no `subtotal` template on cart. It is only a value. You will need to edit the `footer` template of the cart to change that.

We also do not allow changing of the price like that because it could cause inconsistencies between the cart and checkout. The only view data that can be passed into the line items comes from the cart view data. This is because line items are not full components. 

Considering this other issue that you opened https://github.com/Shopify/buy-button-js/issues/362 I would recommend that you either edit the cart footer message letting your customers know that the tax may vary since this is not currently possible with buy-button-js.

If you are looking for a more custom approach and would still like to do this I recommend using https://github.com/Shopify/js-buy-sdk It is `buy-button-js` without the view layer so it is up to you how to display your products, but the sdk takes care of interacting with shopify. `buy-button-js` is just simply a thin layer on top of that library.

**Comment by sniepoort** [comment]
Ok, so I would have to copy all of the footer markup? 

I don't see how it can cause inconsistencies, since it's just view data. 
But are you saying it's impossible for me to modify the line item price?

Seeing as I've got almost everything working, it's not to my advantage to change over to the js-buy-sdk. And a message in the footer saying there's inconsistencies in the tax rate isn't exactly very user friendly.

**Comment by tanema** [comment]
I kept playing around with it and turns out you can modify all of this stuff.

```
  "cart": {
    "viewData": {
      modifyLinePrice: function () {
        return parseFloat(this.data.price) / 2.0;
      },
      mySubtotal: function () {
        return this.data.subtotal + "$$$$$$";
      }
    },
    templates: {
      footer: `{{^data.isEmpty}}
            <div class="{{data.classes.cart.footer}}" data-element="cart.footer">
              <p class="{{data.classes.cart.subtotalText}}" data-element="cart.total">{{data.text.total}}</p>
              <p class="{{data.classes.cart.subtotal}}" data-element="cart.subtotal">{{data.mySubtotal}}</p>
              <p class="{{data.classes.cart.notice}}" data-element="cart.notice">{{data.text.notice}}</p>
              <button class="{{data.classes.cart.button}}" type="button" data-element="cart.button">{{data.text.button}}</button>
            </div>
           {{/data.isEmpty}}`,
    }
  },
  "lineItem": {
    "templates": {
      "price": '<span class="shopify-buy__cart-item__price" data-element="lineItem.price">{{data.modifyLinePrice}}</span>',
    },
  },

```

I still don't recommend altering pricing in your view but this is how it would be done.
