### ISSUE TITLE
Custom font not showing on mobile devices.

### ISSUE THREAD

**Issue by SpencerMiller23** [Shopify/buy-button-js#387]
I changed the font for the buy button text to the custom font I am using across my site. The change worked fine on desktop, however when viewing the page on mobile devices, the font goes to the default google font. I would like to be able to use the custom font on all devices ideally.

**Comment by Mesuva** [comment]
When you're using the iframe method of embedding you're only able to use fonts that Shopify has made available I believe (same ones that are available when you create a buy button from their admin).

You may be seeing the font you want on your desktop because you've got that installed as a desktop font. Your browser is using that font because it's found it installed, but what it's not doing is using the font that you've linked on your site.

On mobiles the font you've selected simply isn't installed.

So what you'd have to do is to display the product with iframe set to false, then style it up as necessary.

**Comment by rebeccajfriedman** [comment]
At this time, BuyButton.js only supports Google fonts.
