### ISSUE TITLE
Which URL for production use?

### ISSUE THREAD

**Issue by Mesuva** [Shopify/buy-button-js#388]
I've noticed that the buy-button script URL is different between what is in the doco, versus what Shopify includes in the cut-and-paste script for buy buttons.

The doco suggests:
http://sdks.shopifycdn.com/buy-button/0.1.34/buybutton.js

But the cut-and-paste code has this:
https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js

This works very similar, but doesn't appear to be the exact same script. Functions like ShopifyBuy.UI.onReady are available in this version, but not in the doco linked one.

I also noticed that this is active
https://sdks.shopifycdn.com/buy-button/latest/buybutton.js
From a glance this looks like a minfied version of the script referred to in the doco. 

Which script is recommended for longer term use in something like a CMS add-on?

**Comment by tanema** [comment]
Hey @Mesuva so there are a few scenarios that you want to use the urls

- The first url http://sdks.shopifycdn.com/buy-button/0.1.34/buybutton.js is good for making sure you have that specific version of the library. This is probably a good option for you so that the library/extension you are developing is stable even if we release breaking changes.
- The cut-and-paste code is a different version of buybutton.js that adds a bit more support for those that primarily use cut-and-paste.
- The last link that you have is just a pointer to the most recent release of the library. You could use this to always stay up to date. We generally try to keep our api backward compatible so generally any releases would work in the future but there would be bug fixes and performance improvements released. 

Overall I would recommend the last link to point to so that you stay up to date however if you have concerns about differences in releases I would use the first link. Overall if you are developing an add-on like you said in your email I would recommend not using our link but instead vendoring the script into your own code.

**Comment by Mesuva** [comment]
Thanks @tanema for the break down, I think I'll look to include a local copy of the script, to control versioning myself.

The latest/buybutton.js script isn't completely compressed and is 339KB, it's actually bigger than the uncompressed 0.1.34 version or the storefront one.

If I compress the 0.1.34 version myself I can get it to ~167KB, so there's some advantages to handling it with a local version in that regard.

**Comment by stestone** [comment]
Just wanted to agree that this should be documented somewhere. The documentation does mention to use 0.1.34 but then it also says to use the new format for buildClient that doesn't require the apiKey or appId, but 0.1.34 still appears to use this old format. When I use the "latest" build it appears to use the newer documented format.

**Comment by robskrob** [comment]
@tanema thank you for the breakdown. `http://sdks.shopifycdn.com/buy-button/0.1.34/buybutton.js` seems to have been the "latest" version for a long time now. Is this version `0.1.34`  still the latest? In the project's [tags](https://github.com/Shopify/buy-button-js/tags) I see the latest version is `v0.9.1`. So if one wanted to specify the latest version why is it `0.1.34` in the CDN link and not `0.9.1`? Maybe I am missing something with version conventions?

**Comment by rebeccajfriedman** [comment]
@robskrob The latest version is `0.9.1`. The link in the docwas meant to be an example, and is not updated every time there is a new release. I've opened a PR to be more explicit in the documentation.
