### ISSUE TITLE
myshopify.com domain is exposed during buy-button checkout

### ISSUE THREAD

**Issue by esoikie** [Shopify/buy-button-js#409]
### Problem

Merchant is concerned that their .myshopify.com domain is visible for a moment in the pop-up window during checkout when using the buy button.

### Scope

1 Merchant reporting.

### Examples
https://screenshot.click/31-57-96wtl-toyak.mp4
[zendesk ticket](https://shopify.zendesk.com/agent/tickets/6761685)
[Internal Dash](https://app.shopify.com/services/internal/shops/17493143)
[Page with Buy Button](https://www.offre.wizzydeals.com/)

### Expected vs Actual
Expect that when a custom domain has been set as default for a store, the .myshopify.com domain is never exposed to the customer.  Actual is that the Buy Button utilizes the .myshopify.com subdomain rather than the store's custom domain.

### More Information
@Shopify/buy-button

**Comment by harisaurus** [comment]
Hi @esoikie - this is not a buy-button only thing. This is how Shopify handles checkout across the board. 

There is, however, an entire project on going that will allow checkout to use a merchant's custom domain rather than the .myshopify domain. I believe its in beta right now and soon to roll out to everyone which will then alleviate this problem for the merchant.
