### ISSUE TITLE
Multiple buttons on same page

### ISSUE THREAD

**Issue by daugaard47** [Shopify/buy-button-js#427]
Probably a simple answer, but how do you add multiple products to a single page?
I currently have to do it by repeating the ui.createComponent funtion like this: (Is there a more simply way?)

```
ui.createComponent('product', {
  id: 489690562602,
  node: document.getElementById('bday'),
  options: { 
    product: {
        width:'100%',
      buttonDestination: 'modal',
      contents: {
        options: false,
        price: false,
        title:false,
        img: false
      },

      styles: {
       button:{
        'width': '100%',
        'height': '60px',
        'background':'#FF6C37',
        ':hover':{'background-color':'#AC441E'},
        ':focus':{'background-color':'#AC441E'},
       },

      }
    }
  }
});

ui.createComponent('product', {
  id: 524242288682,
  node: document.getElementById('pbb'),
  options: { 
    product: {
        width:'100%',
      buttonDestination: 'modal',
      contents: {
        options: false,
        price: false,
        title:false,
        img: false
      },

      styles: {
       button:{
        'width': '100%',
        'height': '60px',
        'background':'#FF6C37',
        ':hover':{'background-color':'#AC441E'},
        ':focus':{'background-color':'#AC441E'},
       },

      }
    }
  }
});

ui.createComponent('product', {
  id: 524113510442,
  node: document.getElementById('tyc'),
  options: { 
    product: {
        width:'100%',
      buttonDestination: 'modal',
      contents: {
        options: false,
        price: false,
        title:false,
        img: false
      },
      styles: {
       button:{
        'width': '100%',
        'height': '60px',
        'background':'#FF6C37',
        ':hover':{'background-color':'#AC441E'},
        ':focus':{'background-color':'#AC441E'},
       },

      }
    }
  }
});
```

Then add the different buttons where needed by calling the ID's like so:

    <div id="bday" align="center"></div>
    <div id="ppb" align="center"></div>
    <div id="tyc" align="center"></div>

Seems like way too much code. Any help would be appreciated. Thanks!

**Comment by daugaard47** [comment]
From what I found it looks like you have to place the product ID's in a ````productSet```` array like this:
````ui.createComponent('productSet', { id: [489690562602, 524242288682, 524113510442],```` 

But not sure how to use the
```` node: document.getElementById('bday'),```` with the above array so i can call other ID's in the HTML
Like this:
`<div id="bday"></div>`
`<div id="ppb"></div>`
`<div id="tyc"></div>`

How would I handle adding multiple products to a page without using collections and by adding the ```` node: document.getElementById('xxx'),```` to match the ````productSet```` array?

**Comment by daugaard47** [comment]
So this is what I'm needing, but not sure how to write the correct code for it:
````ui.createComponent('productSet', {
  id = [489690562602,524100337706,524102565930],

  node(id[0]).getElementById('bday'),
  node(id[1]).getElementById('gws'),
  node(id[2]).getElementById('toy'),

  options: { etc....
````

**Comment by michelleyschen** [comment]
why not add the products to a collection and display a collection instead?

**Comment by daugaard47** [comment]
Thank you for the reply. I don’t want to do a collection because I need  to add multiple products from 2 different stores. I only want the Button so I can place it wherever I need to on the site. Similar to what the speaker is talking about at the end of the video here: https://youtu.be/CGk_cNi4PRY?t=14m11s 

Thanks,

Chris

**Comment by michelleyschen** [comment]
A few thins to note
1. Even if you are adding products from two different shop, I would still highly suggest that you add the products into two collections and add the collection using buy button instead.

This is because there are CSS written specially for collection display in desktop vs mobile and also spacing in b/t products that using a list of product does not have.

2. Also note that having products in two different shop in one web page will create two different carts. One cart checkout across shops is currently not supported.

If you still want to use a list of products. Here are a few workaround you can do.
1. save your list of product ids in an array, then loop through each item in the array to do `ui. createComponent` inside to create product
2. for `node: document.getElementById('bday'),` in your `createComponent` code. You can either use the same node (all the products will show up in the same node one after another), or delete this options all together and the product will show up on the page either at the start of <body> or where in the html you insert the buy button code

**Comment by daugaard47** [comment]
I didn't think about the multiple carts. hmm.
On your work around, do you have an example of the code written out how you suggested? 
Thank you for the advice. I really appreciate it!
