### ISSUE TITLE
"Variable id of type ID! was provided invalid value"

### ISSUE THREAD

**Issue by brijesh-p** [Shopify/buy-button-js#500]
Hello All,

I am facing the same issue https://github.com/Shopify/js-buy-sdk/issues/536. using the same code, tried "base64encode" as well of my product ID, but getting them the error "Variable id of type ID! was provided invalid value".

Technology: Angular JS.

Please help me here guys. Thanks!

**Comment by chrisallick** [comment]
Yeah, the API appears to be broken. I've tried everything:

For the below snippet of code I've tried:
the based64 string
the product id number you get from decoding and parsing
the string of the base64 decode
And a couple other random options. Nothing works.

Seemingly, it's just broken. My v0 live website works perfectly, but cannot get v1 to work in anyway.

```
this.shopifyClient.product.fetch(pID).then((product) => {
});
```

**Comment by minasmart** [comment]
can you give an example of what you're encoding?

**Comment by chrisallick** [comment]
I suspect the issue this developer is having is that they are not encoding "gid://shopify/Product/<product id<" but rather "<product id>" and are therefore not getting the correct base64 string.

I had a comment but deleted it because I found the source of my issue. A lot of the product ID encoded strings have "=" (equal signs) at the end of them and at some point in passing that code around I was dropping the trailing equal signs. When I fixed that client.product.fetch(base64_gid_string) worked.

**Comment by minasmart** [comment]
the `=` signs are actually padding characters that need to stay there since a base64 hash needs to be a multiple of 4 characters long.

I'm guessing it's likely that they may be attempting to encode the raw id outside of a GID URI format, which will give you a base64 encoded string, but not the right one.

**Comment by juanpasolano** [comment]
I am having this same issue but for some reason passing the same string as a variable is what is failing

In this example if I pass the string directly to the product It works
<img width="1265" alt="Screen Shot 2020-09-01 at 8 21 52 PM" src="https://user-images.githubusercontent.com/1621720/91921344-e46cc200-ec90-11ea-9c87-b8c5e39ddc1d.png">

But if it comes as a variable it fails
<img width="1280" alt="Screen Shot 2020-09-01 at 8 21 59 PM" src="https://user-images.githubusercontent.com/1621720/91921378-fd757300-ec90-11ea-8835-342bb4f6d71c.png">

Why would this happen?
