### ISSUE TITLE
Updating cart after removing item

### ISSUE THREAD

**Issue by TomSinclair** [Shopify/buy-button-js#504]
When removing a line item completely (setting quantity to 0), the cart total and 'lineItemCache' do not update. Only when updating another line item does the cart total and 'lineItemCache' update correctly.

It is not possible to get the empty cart message to appear. When refreshing the page, the cart appears empty.

This only occurs when using the non-iframe cart. The iframe cart works fine.

<img width="700" alt="shopify-cart" src="https://user-images.githubusercontent.com/522837/45823488-b67d5580-bce5-11e8-908d-044cef11b881.png">

**Comment by rmykolas** [comment]
Hey @TomSinclair, has this issue been solved? If yes, how?

**Comment by TomSinclair** [comment]
No. We changed how we implemented Shopify on the site as we were informed by the Shopify devs that the buy button is not as flexible as what we were wanting to do.

**Comment by rmykolas** [comment]
To anyone who's run into the same issue, I think I have the solution:

If you're creating a completely new CSS style for the cart drawer outside of the iframe, you CANNOT remove the "flipOut" animation from .shopify-buy__cart-item.is-hidden element.

I'm not sure what the actual triggers in the JS of the Buy Button are, but it seems to be listening for that animation to happen to clear the cart and show the "Cart Empty" notice.

You can obviously style the "flipOut" animation the way you wnt, but regardless of what you do, the CSS for that element must be:

`.shopify-buy__cart-item.is-hidden {
animation-name: flipOut;
}`

Found this after a lot of time wasted and hair pulled, so hopefully, this helps someone and this potentially could be fixed in the Buy Button itself.

Cheers.

**Comment by AnabelleRajotte** [comment]
You can add custom event to the DOM by adding key-value pairs to the DOMEvents object of the cart, like so :
`'click .shopify-buy__quantity-decrement': (e, target) => {},`

`.shopify-buy__quantity-decrement` is the default class for the arrow down option. If you bind your event to this class it will prevent the event from happening, but if you bind your click on another class everything will continue working as expected but inside the function you will be able to check if the quantity is 0, and do whatever you want with this information. You can modify the classes and the template easily, just look at the doc to do that.
